server:
    port: 9005
    servlet:
        session:
            timeout: 30m
spring:
    datasource:
        url: jdbc:mysql://localhost/hg?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
        username: root
        password: root
    jackson:
        property-naming-strategy: SNAKE_CASE
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
